# Generated by Django 5.1.1 on 2025-01-05 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cocktail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(blank=True, choices=[('shaken', 'Shaken'), ('stirred', 'Stirred'), ('built', 'Built'), ('frozen', 'Frozen'), ('blended', 'Blended')], max_length=10, null=True)),
                ('style', models.CharField(blank=True, choices=[('tiki', 'Tiki'), ('modern', 'Modern'), ('sour', 'Sour')], max_length=10, null=True)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('creator', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ingredient_type', models.CharField(choices=[('spirit', 'Spirit'), ('modified_spirit', 'Modified Spirit'), ('citrus', 'Citrus'), ('bitters', 'Bitters'), ('liqueur', 'Liqueur'), ('sweetener', 'Sweetener'), ('fruit_puree', 'Fruit/Puree'), ('herb_spice', 'Herb/Spice'), ('garnish', 'Garnish'), ('dairy_cream', 'Dairy/Cream'), ('syrup_flavoring', 'Syrup/Flavoring'), ('vegetable', 'Vegetable'), ('wine_fortified_wine', 'Wine/Fortified Wine'), ('extract', 'Extract'), ('ice', 'Ice')], max_length=20)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('abv', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Alcohol by Volume (%)')),
                ('sweetness', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Sweetness (%)')),
                ('acid', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Acid (%)')),
                ('instructions', models.TextField(blank=True, null=True, verbose_name='How to create')),
            ],
        ),
        migrations.CreateModel(
            name='CocktailIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, choices=[('Slice', 'slice'), ('Wedge', 'wedge'), ('Drop', 'drop'), ('Dash', 'dash'), ('Milliliter', 'ml'), ('Ounce', 'oz'), ('Cup', 'c')], max_length=20, null=True)),
                ('cocktail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='core.cocktail')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ingredient')),
            ],
        ),
    ]
